allprojects {
    repositories {
        google()
        mavenCentral()
    }

    ext {
        kotlin_version = '1.9.22'
        compileSdkVersion = 35
        minSdkVersion = 23
        targetSdkVersion = 35
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    if (project.name != "app") {
        project.ext.set('flutter', [
            compileSdkVersion: 35,
            minSdkVersion: 23,
            targetSdkVersion: 35
        ])
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}